services:
  php-fpm:
    image: ghcr.io/botlane-feeder/tryingtech-slim:0.2.0
#    build:
#      context: .
#      dockerfile: configs/php-fpm/Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "9080:80"
    networks:
      - app-network
    depends_on:
      - php-fpm

  mongodb:
    image: mongodb/mongodb-community-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
